export const metadata = {
    title: " Next Pizza",
    description: "Generated by create next app",
  };
  
  export default function DashboardLayout({children,}: { 
    children: React.ReactNode }) {
  
    return (
      <html lang="en">
        DASHBOARD HEADER
        <body>
         {children}
        </body>          
      </html>
    );
  }